// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is auto-generated by ds_builder

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

class RouteNames {
  static const String home = '/';
  static const String profile = '/profile';
  static const String detail = '/detail/:id';
}

// Example usage in your app:
// 
// final goRouter = GoRouter(
//   routes: [
//     GoRoute(
//       path: '/',
//       builder: (context, state) => HomePage(),
//     ),
//     GoRoute(
//       path: '/profile',
//       builder: (context, state) => ProfilePage(),
//     ),
//     GoRoute(
//       path: '/detail/:id',
//       builder: (context, state) {
//         final id = state.pathParameters['id'];
//         return DetailPage(id: id ?? '');
//       },
//     ),
//   ],
// );
