// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is auto-generated by ds_builder

class R {
  R._();

  // Image assets
  static const String logoSvg = 'assets/images/logo.svg';
  static const String backgroundPng = 'assets/images/background.png';
  static const String avatarPng = 'assets/images/profile/avatar.png';

  // File assets
  static const String configJson = 'assets/config.json';
}

// Usage in your code:
//
// import 'res/r.dart';
//
// Image.asset(R.logoSvg);
// Image.asset(R.backgroundPng);
// SvgPicture.asset(R.avatarPng);
